services:
  langgraph-agent:
    image: mwaeckerlin/langgraph-agent
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URI: postgresql://langgraph:password@db/langgraph
      OPENAI_BASE_URL: http://litellm:4000
      LLM_MODEL: gpt-4o-mini
      GRAPHS_DIR: /app/graphs
